[package]
name = "rust-array-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
essential-types = "0.3.0"
anyhow = "1.0.90"

